<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>Snek-Team</Company>
    <Authors>Snek-Team</Authors>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\favicon.ico" />
    <None Remove="Images\Snek_PNG.png" />
    <Resource Include="Images\favicon.ico" />
    <Resource Include="Images\Snek_PNG.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Snek.Core\Snek.Core.csproj" />
    <ProjectReference Include="..\Snek.Infrastructure\Snek.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
</Project>
