// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snek.Infrastructure.Persistence;

#nullable disable

namespace Snek.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SnekDbContext))]
    partial class SnekDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ArbeitenMitwirkende", b =>
                {
                    b.Property<int>("ArbeitenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MitwirkendeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArbeitenId", "MitwirkendeId");

                    b.HasIndex("MitwirkendeId");

                    b.ToTable("ArbeitenMitwirkende");
                });

            modelBuilder.Entity("Snek.Core.Models.Arbeiten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Art")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Arbeiten");
                });

            modelBuilder.Entity("Snek.Core.Models.Mitwirkende", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mitwirkende");
                });

            modelBuilder.Entity("Snek.Core.Models.Zeiten", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArbeitenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minuten")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sekunden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stunden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArbeitenId");

                    b.ToTable("Zeiten", t =>
                        {
                            t.HasCheckConstraint("CK_Zeiten_Minuten", "Minuten >= 0 AND Minuten < 60");

                            t.HasCheckConstraint("CK_Zeiten_Sekunden", "Sekunden >= 0 AND Sekunden < 60");

                            t.HasCheckConstraint("CK_Zeiten_Stunden", "Stunden >= 0");
                        });
                });

            modelBuilder.Entity("ArbeitenMitwirkende", b =>
                {
                    b.HasOne("Snek.Core.Models.Arbeiten", null)
                        .WithMany()
                        .HasForeignKey("ArbeitenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Snek.Core.Models.Mitwirkende", null)
                        .WithMany()
                        .HasForeignKey("MitwirkendeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Snek.Core.Models.Zeiten", b =>
                {
                    b.HasOne("Snek.Core.Models.Arbeiten", "Arbeiten")
                        .WithMany("Zeiten")
                        .HasForeignKey("ArbeitenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arbeiten");
                });

            modelBuilder.Entity("Snek.Core.Models.Arbeiten", b =>
                {
                    b.Navigation("Zeiten");
                });
#pragma warning restore 612, 618
        }
    }
}
